/**
 * Licensed to JumpMind Inc under one or more contributor
 * license agreements.  See the NOTICE file distributed
 * with this work for additional information regarding
 * copyright ownership.  JumpMind Inc licenses this file
 * to you under the GNU Affero General Public License, version 3.0 (AGPLv3)
 * (the "License"); you may not use this file except in compliance
 * with the License.
 *
 * You should have received a copy of the GNU Affero General Public License,
 * version 3.0 (AGPLv3) along with this library; if not, see
 * <http://www.gnu.org/licenses/>.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.jumpmind.db.platform.hana;

import java.sql.Types;

import org.jumpmind.db.model.Column;
import org.jumpmind.db.model.Table;
import org.jumpmind.db.platform.AbstractDdlBuilder;
import org.jumpmind.db.platform.DatabaseNamesConstants;
import org.jumpmind.db.platform.IDdlBuilder;

public class HanaDdlBuilder extends AbstractDdlBuilder implements IDdlBuilder {
    public HanaDdlBuilder() {
        super(DatabaseNamesConstants.HANA);
        databaseInfo.setGeneratedColumnsSupported(true);
        databaseInfo.setSystemIndicesReturned(true);
        databaseInfo.setAutoIncrementUpdateAllowed(true);
        databaseInfo.addNativeTypeMapping(Types.VARCHAR, "NVARCHAR", Types.NVARCHAR);
        databaseInfo.addNativeTypeMapping(Types.CHAR, "NCHAR", Types.NCHAR);
        databaseInfo.addNativeTypeMapping(Types.LONGVARBINARY, "BLOB", Types.BLOB);
        databaseInfo.addNativeTypeMapping(Types.LONGVARCHAR, "NCLOB", Types.NCLOB);
        databaseInfo.addNativeTypeMapping(Types.CLOB, "NCLOB", Types.NCLOB);
    }

    @Override
    protected void writeColumnAutoIncrementStmt(Table table, Column column, StringBuilder ddl) {
        ddl.append(" GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) ");
    }
}
