package org.jumpmind.db.platform.hana;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Types;

import org.jumpmind.db.platform.DatabaseInfo;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class HanaDdlBuilderTest {
    private HanaDdlBuilder ddlBuilder;

    @BeforeEach
    void setUp() {
        ddlBuilder = new HanaDdlBuilder();
    }

    @Test
    void testConstructor() {
        assertNotNull(ddlBuilder);
        DatabaseInfo hanaDatabaseInfo = ddlBuilder.getDatabaseInfo();
        assertTrue(hanaDatabaseInfo.isGeneratedColumnsSupported());
        assertTrue(hanaDatabaseInfo.isSystemIndicesReturned());
        assertTrue(hanaDatabaseInfo.isAutoIncrementUpdateAllowed());
        assertEquals("NVARCHAR", hanaDatabaseInfo.getNativeType(Types.VARCHAR));
        assertEquals("NCHAR", hanaDatabaseInfo.getNativeType(Types.CHAR));
        assertEquals("BLOB", hanaDatabaseInfo.getNativeType(Types.LONGVARBINARY));
        assertEquals("NCLOB", hanaDatabaseInfo.getNativeType(Types.LONGVARCHAR));
        assertEquals("NCLOB", hanaDatabaseInfo.getNativeType(Types.CLOB));
    }

    @Test
    void testWriteColumnAutoIncrementStmt() {
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.writeColumnAutoIncrementStmt(null, null, ddl);
        assertEquals(" GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) ", ddl.toString());
    }
}
