apply from: symAssembleDir + '/common.gradle'

    description = 'Library that contains the jdbc implementation for symmetric-db'

    dependencies {
        api project(":symmetric-db")
        api ("org.apache.commons:commons-dbcp2:$commonsDbcpVersion") {
            exclude group: 'commons-logging'
        }
        api "org.springframework:spring-jdbc:$springVersion"

        compileOnly "com.h2database:h2:$h2Version"

        testImplementation project(path: ':symmetric-util', configuration: 'testArtifacts')
        testImplementation "com.h2database:h2:$h2Version"
        testImplementation "com.mysql:mysql-connector-j:$mysqlVersion"
        testImplementation "org.postgresql:postgresql:$postgresqlVersion"
        testImplementation 'com.oracle.database.jdbc:ojdbc11:23.4.0.24.05'

        testImplementation "net.sourceforge.jtds:jtds:$jtdsVersion"
        testImplementation "org.jumpmind.symmetric.module:jconn4:16.0"
        testImplementation "org.apache.derby:derby:$derbyVersion"
        testImplementation "org.apache.derby:derbytools:$derbyVersion"
        testImplementation "org.hsqldb:hsqldb:$hsqldbVersion"
        testImplementation "org.xerial:sqlite-jdbc:$sqliteVersion"
        testImplementation "org.jumpmind.symmetric.module:db2jcc:9.7"
        testImplementation "org.firebirdsql.jdbc:jaybird:6.0.1"
        testImplementation "jakarta.resource:jakarta.resource-api:2.1.0"
        testImplementation "org.jumpmind.symmetric.module:ifxjdbc:1.0"
        testImplementation "org.jumpmind.symmetric.module:ifxlang:1.0"
        testImplementation "org.jumpmind.symmetric.module:interclient:13.2.0"
        testImplementation "org.mariadb.jdbc:mariadb-java-client:3.3.3"
        testImplementation "com.microsoft.sqlserver:mssql-jdbc:$mssqlVersion"
        testImplementation "org.jumpmind.symmetric.module:nuodb-jdbc:3.3.1"
        testImplementation "org.jumpmind.symmetric.module:tibero:6"
        testImplementation "org.voltdb:voltdbclient:8.4.3"
        testImplementation "net.sf.jt400:jt400:10.7"
        testImplementation "com.singlestore:singlestore-jdbc-client:1.0.2"
        testImplementation "net.snowflake:snowflake-jdbc:3.13.34"
        testImplementation "org.duckdb:duckdb_jdbc:1.1.2"
        testImplementation "com.exasol:exasol-jdbc:25.2.2"
        testImplementation "org.apache.hive:hive-jdbc:4.0.1:standalone"
        testImplementation "com.databricks:databricks-jdbc:2.7.3"
        testImplementation "com.sap.cloud.db.jdbc:ngdbc:2.24.8"
        
        implementation 'software.amazon.awssdk:s3:2.40.12'
	    implementation 'software.amazon.awssdk:redshift:2.40.12'	
	    
        
    }
