name: Build and Test
on:
  workflow_call:

  workflow_dispatch:
    inputs:
      skip-tests:
        description: 'Skip the test execution step?'
        type: string
        required: false
        default: 'false'
      skip-style-check:
        description: 'Skip the style check step?'
        type: string
        required: false
        default: 'false'

jobs:
  build-test:
    name: Build and Test
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.0.1

      - name: Build with Gradle
        run: |
          ./gradlew clean develop
        working-directory: symmetric-assemble

      - name: Test with Gradle
        if: ${{ inputs.skip-tests != 'true' }}
        run: |
          ./gradlew test
        working-directory: symmetric-assemble

      - name: Style check with Gradle
        if: ${{ inputs.skip-style-check != 'true' }}
        run: |
          ./gradlew spotlessJavaCheck
        working-directory: symmetric-assemble  
