name: Sonar Scan
on:
  push:
    branches:
      - 'release/**'
  workflow_call:

jobs:
  sonar-scan:
    name: Sonar Scan
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.0.1

      - name: Cache Sonar packages
        uses: actions/cache@v5.0.4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run build and Sonar analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew clean build -x spotlessJavaCheck sonar --info
        working-directory: symmetric-assemble
