buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }

    dependencies {
        // classpath 'org.asciidoctor:asciidoctorj-pdf:4.0.4'
        classpath 'org.asciidoctor:asciidoctor-gradle-jvm:4.0.4'
        classpath 'com.diffplug.spotless:spotless-plugin-gradle:7.0.3'
        classpath 'com.bmuschko:gradle-docker-plugin:9.4.0'
        classpath 'org.jacoco:org.jacoco.ant:0.8.12'
    }
}

plugins {
    id "org.sonarqube" version "6.2.0.5505"
    id 'com.vaadin' version "$vaadinPluginVersion" apply false
    id 'org.asciidoctor.jvm.convert' version '4.0.4' apply false
    id 'eu.kakde.gradle.sonatype-maven-central-publisher' version '1.0.6' apply false
}

apply plugin: 'java-library'
apply plugin: 'idea'
apply plugin: 'eclipse'
apply plugin: 'com.bmuschko.docker-remote-api'
apply plugin: 'jacoco'

allprojects {
    apply plugin: 'com.diffplug.spotless'
    spotless {
      java {
        eclipse().configFile(project.rootDir.toString() + '/formatter.eclipse.xml')
      }
    }
}

task develop {
    dependsOn tasks.cleanEclipse, tasks.eclipse, tasks.cleanIdea, tasks.idea, tasks.compileTestJava
}

idea {
    module {
        testResources = files([])
        testSources = files(['src/test/java'])
        resourceDirs += file('src/test/resources')
        excludeDirs += file('bin')
        excludeDirs += file('build')
        excludeDirs += file('dist')
        excludeDirs += file('node_modules')
        downloadJavadoc = true
        downloadSources = true
    }
    project {
        ipr {
            //you can tinker with the output *.ipr file before it's written out
            withXml {
                // turn on annotation processing
                def node = it.asNode().children()[0].get('annotationProcessing')[0];
                node.attributes().clear();
                node.appendNode('profile',['default':'true', 'name':'Default', 'enabled':'true'])

            }
        }
    }
}

task buildScriptDependencies(type: org.gradle.api.tasks.diagnostics.DependencyReportTask) {
    configurations = project.buildscript.configurations
}

//This section applies the sonarqube plugin to all subprojects and then specifies an xml report path in symmetric-assemble
subprojects {
    apply plugin: 'org.sonarqube'
    sonar {
        properties {
            property 'sonar.coverage.jacoco.xmlReportPaths', "${rootDir}/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml"
            //this could be set to sonar.coverage.exclusions as that only excludes these files from coverage
            property "sonar.coverage.exclusions", "**/*.ad, **/*.js, **/*.c"
            property "sonar.exclusions","**/ui/**"
            property "sonar.scm.disabled", "true"    
        }
    }
    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}

if (project.properties.containsKey('pro')) {
    install.enabled = false
    uploadArchives.enabled = false
} else {
    apply from: symAssembleDir + '/common.gradle'
}

//used to specify the jacoco version
jacoco {
    toolVersion = "0.8.12"
}

task codeCoverageReport(type: JacocoReport) {
    dependsOn ':symmetric-client:compileTestJava'
    dependsOn ':symmetric-client:test'
    dependsOn ':symmetric-client:jacocoTestReport'
    dependsOn ':symmetric-client:processTestResources'
    dependsOn ':symmetric-core:compileTestJava'
    dependsOn ':symmetric-core:test'
    dependsOn ':symmetric-core:jacocoTestReport'
    dependsOn ':symmetric-core:processTestResources'
    dependsOn ':symmetric-csv:test'
    dependsOn ':symmetric-db:compileTestJava'
    dependsOn ':symmetric-db:test'
    dependsOn ':symmetric-db:jacocoTestReport'
    dependsOn ':symmetric-db:processTestResources'
    dependsOn ':symmetric-io:compileTestJava'
    dependsOn ':symmetric-io:test'
    dependsOn ':symmetric-io:jacocoTestReport'
    dependsOn ':symmetric-io:processTestResources'
    dependsOn ':symmetric-jdbc:compileTestJava'
    dependsOn ':symmetric-jdbc:test'
    dependsOn ':symmetric-jdbc:jacocoTestReport'
    dependsOn ':symmetric-jdbc:processTestResources'
    dependsOn ':symmetric-server:compileTestJava'
    dependsOn ':symmetric-server:test'
    dependsOn ':symmetric-server:jacocoTestReport'
    dependsOn ':symmetric-server:processTestResources'
    dependsOn ':symmetric-sqlexplorer:test'
    dependsOn ':symmetric-util:compileTestJava'
    dependsOn ':symmetric-util:test'
    dependsOn ':symmetric-util:jacocoTestReport'
    dependsOn ':symmetric-util:processTestResources'
    dependsOn ':symmetric-wrapper:test'
    dependsOn ':test'
    // Gather execution data from all subprojects
    executionData = files(
    subprojects.collect { subproject ->
        file("${subproject.buildDir}/jacoco/test.exec")
    }.findAll { it.exists() }
    )
    
    allprojects.each {
        sourceSets it.sourceSets.main
    }
    //controls what reports are generated. XML is needed for sonarqube to run. HTML is for a human readable option to check things
    reports {
        xml.required = true
        html.required = true        
        xml.outputLocation = file("${rootDir}/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml")
        html.outputLocation = file("${rootDir}/build/reports/jacoco/codeCoverageReport/codeCoverageReport.html")
    }
}


//forces sonar to require codeCoverageReport which runs all of the tests
tasks['sonar'].with {
    dependsOn codeCoverageReport
}

task generateJavadoc(type: Javadoc) {
    destinationDir = new File(buildDir, 'doc/javadoc')
    title = "SymmetricDS API $version"
    group = 'SymmetricDS'
    description = 'Generate JavaDoc HTML pages for API documentation'
    options.addStringOption 'Xdoclint:none', '-quiet'
    
    subprojects.each { proj ->
        proj.tasks.withType(Javadoc).each { javadocTask ->
            source += javadocTask.source
            classpath += javadocTask.classpath
            excludes += javadocTask.excludes
            includes += javadocTask.includes
        }
    }
}

def isLatest = project.hasProperty("latest") && project.property("latest") == "true"

task publishJavadoc {
    dependsOn generateJavadoc
    group = 'SymmetricDS'
    description = 'Publish javadoc to SourceForge website'
    doLast {
        ant.taskdef(name: 'scp', classname: 'org.apache.tools.ant.taskdefs.optional.ssh.Scp',
        classpath: configurations.sshAntTask.asPath)

        ant.scp(
            todir: "$sourceforgeUser:$sourceforgePassword@web.sourceforge.net:/home/project-web/symmetricds/htdocs/doc/$majorMinorVersion",
            trust: 'true',
            verbose: 'true') {
            fileset(dir: "$buildDir/doc") { include(name: 'javadoc/')
            }
        }
    }
}

task buildSymmetric {
    group = 'SymmetricDS'
    description = 'Build software, documentation, and distribution ZIP files'
    dependsOn ':symmetric-server:serverDistZip'
}

interface InjectedExecOps {
    @Inject
    ExecOperations getExecOps()
}

tasks.register('pushArtifactToSourceForge') {
	dependsOn buildSymmetric
	doLast {
        ant.taskdef(name: 'scp', classname: 'org.apache.tools.ant.taskdefs.optional.ssh.Scp',
        classpath: configurations.sshAntTask.asPath)

        println "Publishing server distribution to source forge"
        ant.scp(
            todir: "$sourceforgeUser:$sourceforgePassword@frs.sourceforge.net:/home/frs/project/symmetricds/symmetricds/symmetricds-$majorMinorVersion",
            trust: 'true',
            verbose: 'true') {
            fileset(dir: "../symmetric-server/build/distributions/") { 
                include(name: 'symmetric-server-' + version + '.zip')
            }
        }
    }
}

tasks.register('markAsLatestOnSourceForge') {
	dependsOn pushArtifactToSourceForge
	if (isLatest) {    
        println "Setting latest file on SourceForge to symmetricds-$majorMinorVersion/symmetric-server-" + version + ".zip"
        def injected = project.objects.newInstance(InjectedExecOps)
		doLast {
	        injected.execOps.exec {
	            commandLine "curl", "-s", "-S", "-H", "Accept: application/json", "-X", "PUT",
                    "-d", "default=windows&default=mac&default=linux&default=bsd&default=solaris&default=others",
                    "-d", "api_key=$sourceforgeApiKey",
                    "https://sourceforge.net/projects/symmetricds/files/symmetricds/symmetricds-$majorMinorVersion/symmetric-server-" + version + ".zip"
	        }
	    }
    }
}

task publishSymmetric {
    dependsOn markAsLatestOnSourceForge
    group = 'SymmetricDS'
    description = 'Publish software to SourceForge website'
}

task releaseSymmetric {
    dependsOn publishSymmetric
    dependsOn tasks.getByPath('symmetric-server:publishDoc')
    group = 'SymmetricDS'
    description = 'Publish software to SourceForge website and online documentation to SymmetricDS website'
}


docker {
    registryCredentials {
        username = "$dockerUser".toString()
        password = "$dockerPassword".toString()
    }
}

task copyDockerReadme(type: Copy) {
    from "Dockerfile.md"
    into "../symmetric-server/build/distributions/README.md"
}

task copyDockerfile(type: Copy) {
    dependsOn copyDockerReadme
    from "Dockerfile"
    into "../symmetric-server/build/distributions"
}

task buildImage(type: com.bmuschko.gradle.docker.tasks.image.DockerBuildImage) {
    dependsOn copyDockerfile
    dependsOn tasks.getByPath(':symmetric-server:serverDistZip')
    inputDir = file("../symmetric-server/build/distributions")
    images = ["jumpmind/symmetricds:latest", "jumpmind/symmetricds:${version}".toString(), "jumpmind/symmetricds:${majorMinorVersion}".toString()]
    buildArgs = ["SERVER_ZIP":"symmetric-server-${version}.zip"]
}

task publishDocker(type: com.bmuschko.gradle.docker.tasks.image.DockerPushImage) {
    dependsOn buildImage
    images.empty()
    images.add("jumpmind/symmetricds:${version}".toString())
    images.add("jumpmind/symmetricds:${majorMinorVersion}".toString())
    
    if (isLatest) {
    images.add("jumpmind/symmetricds:latest")
    }

    doLast {
        println "Pushing Docker Image to the jumpmind/symmetricds Repository"
    }
}
