symAssembleDir=../symmetric-assemble
version=3.17.x-SNAPSHOT
scmVersion=?
scmBranch=?
deployUser=?
deployPassword=?
deployUploadUrl=?
docFormat=html5
publishUser=?
publishPassword=?
publishPort=?
publishServer=symmetricds.org
sourceforgeUser=?
sourceforgePassword=?
sourceforgeApiKey=?
vaadinVersion=24.9.3
vaadinPluginVersion=24.9.3
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx4096M
latestPreviousVersion=3.16.6
restAPISecret=?
dockerUser=?
dockerPassword=?
githubToken=?
